FirstBlog/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views
from .import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog', include('blog.urls')),
    url(r'^aftershiptracking/', include('aftershiptracking.urls')),
    url(r'^articles/', include('articles.urls')),
    url(r'^automation/', include('automation.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^about/$', views.about),
    url(r'^raasidetails', include('raasidetails.urls')),
    url(r'^$', article_views.article_list, name="home")
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.conf.urls import url
from .import views

app_name='accounts'

urlpatterns = [
    url(r'^signup/$', views.signup_view, name="signup"),
    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.logout_view, name='logout')


]

articles/urls.py
from django.conf.urls import url
from .import views

app_name = "articles"

urlpatterns = [

    url(r'^$', views.article_list, name="list"),
    url(r'^create/$', views.article_create, name='create'),
    url(r'^(?P<slug>[\w-]+)/$', views.article_details, name="detail"),

]

blog/urls.py
from django.conf.urls import url
from django.contrib import admin
from .import views


urlpatterns = [

   url(r'^admin/', admin.site.urls),
   url(r'^$', views.index, name='index'),

]

templates/base_layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Article</title>
        <link rel="stylesheet" href="{% static 'styles.css' %}"/>
    </head>
    <body>
        <header class="wrapper">
            <h1><a href="{% url 'home' %}"><img src="{% static 'logo.png' %}"></a></h1>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                        <li>
                            <form class="logout-link" action="{% url 'accounts:logout' %}" method = "POST">
                                {%csrf_token %}
                                <button type="submit">Logout</button>
                            </form>
                        </li>
                        <li><a href="{% url 'articles:create' %}" class="highlight">New Article</a></li>
                    {% else %}
                        <li><a href="{% url 'accounts:login' %}">Login</a></li>
                        <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header>
    <div class="wrapper">
        {% block content %}
        {% endblock %}
    </div>
    </body>
</html>

templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>